### PR TITLE
Transfer learning

### PR DESCRIPTION
**Pull request by greenw0lf**
All information can be found in the notebook and README of the repo.

### CODE REVIEW

**Comment by homeSpatula87** [comment]
**The README:** <br>
The README is very clear.

**The notebook:** <br>
I had one small issue with the notebook (while running it in collab).
The 6th cell of the notebook gives a ``` ModuleNotFoundError: No module named 'tensorflow' ``` error:
```
No path "english/" - creating ...
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-e400f66c3a13>](https://localhost:8080/#) in <module>
     17 
     18 # Download + extract pre-trained English model
---> 19 download_pretrained_model()

2 frames
[<ipython-input-6-e400f66c3a13>](https://localhost:8080/#) in download_pretrained_model()
      7     model_dir="english/"
      8     if not os.path.exists("english"):
----> 9         maybe_download("model.tar.gz", model_dir, "https://github.com/coqui-ai/STT/releases/download/v1.4.0/coqui-stt-1.4.0-checkpoint.tar.gz")
     10         print('\nNo extracted pre-trained model found. Extracting now...')
     11         tar = tarfile.open("english/model.tar.gz")

[/usr/local/lib/python3.7/dist-packages/coqui_stt_training/util/downloader.py](https://localhost:8080/#) in maybe_download(archive_name, target_dir, archive_url)
     24         makedirs(target_dir)
     25 
---> 26     if not path_exists_remote(archive_path):
     27         print('No archive "%s" - downloading...' % archive_path)
     28         req = requests.get(archive_url, stream=True)

[/usr/local/lib/python3.7/dist-packages/coqui_stt_training/util/io.py](https://localhost:8080/#) in path_exists_remote(path)
     20     `gs://...`
     21     """
---> 22     from tensorflow.io import gfile
     23 
     24     if is_remote_path(path):

ModuleNotFoundError: No module named 'tensorflow'
```
I though this might be due to the line ```! pip uninstall -y tensorflow; !pip install "tensorflow-gpu==1.15"``` from cell 1.
I went ahead and changed this line to ```!pip install "tensorflow-gpu==1.15"```.
After this change all the notebook ran without further issues.

I'm also wondering why you needed a test and a validation set.

**The results:** <br>
I obtained the following results for the test set: WER: 1.000000, CER: 0.732394, loss: 291.305237.
There are also examples given for best WER.
These are a bit weird, as they are greater than 1 (ad it's weird that these would be the best).
I'm not sure how to interpret the "src:" and "res:" parts of the testing, but especially the "res:" parts seem a bit weird (but maybe it's not).
I have added a pdf of the notebook as an attachment.

I have some thoughts / questions about on these results:
I would be interested in knowing what the WER / CER is like for the data you trained on, since your train set is quite small, could it be that the model over-learned? (The loss for the train set was much lower)

Do you think anything went wrong or could this be reasonable for the amount of data / epochs / difference in language?


[carolos_test_run_transfer_learning_romanian.pdf](https://github.com/greenw0lf/STT/files/9989113/carolos_test_run_transfer_learning_romanian.pdf)

**Comment by greenw0lf** [comment]
I'll address the points one by one:

> The README is very clear.

Glad to hear!

> I had one small issue with the notebook (while running it in collab).

Ah, I was not aware that it would not work because of that line. It worked just fine for me. But, thank you for noticing it and also finding a solution to the problem, I will update the notebook ASAP as well!

> I'm also wondering why you needed a test and a validation set.

It is a common thing to do in machine learning applications. People usually split the data into 3 sets: training, validation, and testing sets. Here's an article that also mentions that: https://www.techtarget.com/searchenterpriseai/definition/data-splitting#:~:text=In%20machine%20learning%2C%20data%20splitting,into%20three%20or%20four%20sets.

It is also important to do so in order to avoid overfitting (which I think still happened in this case, or maybe the training set is too small for the task).

> These are a bit weird, as they are greater than 1 (ad it's weird that these would be the best).

Yes, apparently WER can be higher than 1 (or 100%). Reference: https://en.wikipedia.org/wiki/Word_error_rate#:~:text=Note%20that%20since%20N%20is%20the%20number%20of%20words%20in%20the%20reference%2C%20the%20word%20error%20rate%20can%20be%20larger%20than%201.0%2C%20and%20thus%2C%20the%20word%20accuracy%20can%20be%20smaller%20than%200.0.

> I would be interested in knowing what the WER / CER is like for the data you trained on, since your train set is quite small, could it be that the model over-learned? (The loss for the train set was much lower)

That could be the case. The amount of data is quite small (I think less than an hour of training data), so I would imagine the model being not so generalizable, even if we trained on top of the English model that used much more data and was very accurate.

> Do you think anything went wrong or could this be reasonable for the amount of data / epochs / difference in language?

I am assuming that it is both the different language and the amount of data used to train for the target language (Romanian) that may have impacted the performance. Things I would change are definitely the amount of data used in training (and validation and testing) and the number of epochs. But, due to the time it takes to run the model, it was not as feasible to do that with this notebook.
<br><br>
I hope to have addressed all the points in a clear and understandable way and do let me know if you have any more questions or need more clarifications.

**Comment by homeSpatula87** [comment]
_> It is a common thing to do in machine learning applications. People usually split the data into 3 sets: training, validation, and testing sets._

I know, but the validation set is used for tuning hyper parameters, and I was not sure you you were tuning any hyper parameters based on the validation set. (But maybe you are, or having a validation set is just necessary for the framework you are using)



_> Yes, apparently WER can be higher than 1 (or 100%)._
Ah, okay, clear (maybe still surprising that the final WER is 100%). Maybe the line "Both are measured from 0 to 1, where lower means better." from the README should be altered then.

**Comment by greenw0lf** [comment]
> I know, but the validation set is used for tuning hyper parameters, and I was not sure you you were tuning any hyper parameters based on the validation set. (But maybe you are, or having a validation set is just necessary for the framework you are using)

I think some tuning of the hyperparameters still happens because we are still trying to train a new model. And I think that indeed Coqui needs me to have a validation set specified.

> Ah, okay, clear (maybe still surprising that the final WER is 100%). Maybe the line "Both are measured from 0 to 1, where lower means better." from the README should be altered then.

Oh yeah, great catch, I completely forgot I mentioned that. Thanks!

**Comment by homeSpatula87** [comment]
@s1nayak I am satisfied, and will now merge the pull request.

**Comment by greenw0lf** [comment]
@s1nayak I will give a grade of 10 to Carolos, he has spotted an issue and fixed it himself too and helped me clarify some information in the README. Good job on reviewing!

**Pull request merged**
